[SELC-3811] fix: Refactor Infra
pagopa/selfcare-user pull request #43
Opened 2024-02-05 15:26 UTC by andrea-putzu

#### List of Changes
Refactor: use only one terraform folder with more configuration [ENV]-[µs-name]-[SELC,PNPG]

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-06 10:10 UTC, manuraf commented on infra/container_apps/user/container_app_user.tf
> +            image = "ghcr.io/pagopa/selfcare-user-cdc:${var.image_tag}"
"selfcare-user-cdc" should change in case of user-ms...

2024-02-07 11:03 UTC, Krusty93 commented on infra/container_apps/user/container_app_user.tf
> +          allowInsecure = true
Is internal communication through http or https?

2024-02-07 11:23 UTC, Krusty93 requested changes
Since cdc and ms are two different applications - that can diverge more than simple variable values - I'd define two container app instances with a single environment. I'd also evaluate if using two different TF configurations, e.g.:
- container_apps/user
- container_apps/user-cdc

In any case, we need to handle them with two different pipelines

2024-02-15 09:02 UTC, manuraf commented on infra/container_apps/user-cdc/env/dev/backend.tfvars
> +key                  = "selfcare-user.user-app.tfstate"
could be better to use a different key for user-cdc

2024-02-15 10:56 UTC, merged