[SELC-3924] feat: Added maven settings to set token and access to registry
pagopa/selfcare-user pull request #49
Opened 2024-02-15 16:40 UTC by pierpaolodidato89

#### List of Changes

Added maven settings to set token and access to registry

2024-02-15 16:42 UTC, andrea-putzu approved these changes

2024-02-16 14:21 UTC, Krusty93 requested changes
Creating a dependency between the environment and the Dockerfile is considered a bad practice. A solution for this would be accepting values for `github.actor` and `secrets.GITHUB_TOKEN` through the use of build args. So, both the new step `Maven settings` and `COPY ./.m2/settings.xml` can be removed

2024-02-20 11:34 UTC, andrea-putzu approved these changes

2024-02-20 12:07 UTC, Krusty93 approved these changes
Few suggestions

2024-02-20 12:07 UTC, Krusty93 commented on apps/user-cdc/Dockerfile
> +		 "</servers>\n" \
Can you please use spaces instead of tabs here?

2024-02-20 12:07 UTC, Krusty93 commented on apps/user-cdc/Dockerfile
> +RUN cat settings.xml
Can be removed

2024-02-20 12:07 UTC, Krusty93 commented on apps/user-ms/Dockerfile
> +RUN cat settings.xml
Can be removed

2024-02-20 12:07 UTC, Krusty93 commented on apps/user-cdc/Dockerfile
> +ENV REPO_ID=${REPO_ID} REPO_USERNAME=${REPO_USERNAME} REPO_PASSWORD=${REPO_PASSWORD}
I'd remove the ENV to use ARG in the line below, what you think?

2024-02-20 12:07 UTC, Krusty93 commented on apps/user-ms/Dockerfile
> +ENV REPO_ID=${REPO_ID} REPO_USERNAME=${REPO_USERNAME} REPO_PASSWORD=${REPO_PASSWORD}
I'd remove the ENV to use ARG in the line below, what you think?

2024-02-20 12:07 UTC, Krusty93 commented on infra/container_apps/user-cdc/env/dev/terraform.tfvars
>  prefix    = "selc"
Can be removed, added by module

2024-02-20 12:07 UTC, Krusty93 commented on infra/container_apps/user-ms/env/dev/terraform.tfvars
>  prefix    = "selc"
Can be removed, added by module

2024-02-20 13:25 UTC, Krusty93 approved these changes

2024-02-20 13:28 UTC, merged